package ru.itis.maletskov.internship.model.type;

public enum CommandType {
    CONNECT_ROOM, DISCONNECT_ROOM, CREATE_ROOM, REMOVE_ROOM, RENAME_ROOM, USER_RENAME, USER_BAN,
    USER_MODERATOR, YBOT_FIND, YBOT_HELP, HELP, YBOT_FIVE_LAST_VIDEOS, YBOT_RANDOM_COMMENT
}
